const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  platform: process.platform,
  loadNotes: () => ipcRenderer.invoke('load-notes'),
  saveNotes: (notes) => ipcRenderer.invoke('save-notes', notes),
  listProfiles: () => ipcRenderer.invoke('list-profiles'),
  createProfile: (name) => ipcRenderer.invoke('create-profile', name),
  switchProfile: (id) => ipcRenderer.invoke('switch-profile', id),
  renameProfile: (id, name) => ipcRenderer.invoke('rename-profile', id, name),
  deleteProfile: (id) => ipcRenderer.invoke('delete-profile', id),
  copyIntoProfile: (payload) => ipcRenderer.invoke('copy-into-profile', payload),
  minimize: () => ipcRenderer.send('window-minimize'),
  close: () => ipcRenderer.send('window-close'),
  toggleMaximize: () => ipcRenderer.invoke('window-toggle-maximize'),
  isMaximized: () => ipcRenderer.invoke('is-maximized'),
  onMaximizeChange: (cb) => ipcRenderer.on('maximize-change', (_e, v) => cb(v)),
  toggleFullscreen: () => ipcRenderer.invoke('toggle-fullscreen'),
  isFullscreen: () => ipcRenderer.invoke('is-fullscreen'),
  onFullscreenChange: (cb) => ipcRenderer.on('fullscreen-change', (_e, v) => cb(v)),
  // How fast the window is being dragged, in px per 60Hz frame. Themes that
  // model something physical use it; everything else ignores it.
  onWindowShove: (cb) => ipcRenderer.on('window-shove', (_e, v) => cb(v)),
  toggleAlwaysOnTop: () => ipcRenderer.invoke('toggle-always-on-top'),
  getAlwaysOnTop: () => ipcRenderer.invoke('get-always-on-top'),
  loadSettings: () => ipcRenderer.invoke('load-settings'),
  saveSettings: (settings) => ipcRenderer.invoke('save-settings', settings),
  setBgColor: (color) => ipcRenderer.send('set-bg-color', color),
  growWindow: (w, h) => ipcRenderer.invoke('grow-window', w, h),
  restoreWindow: () => ipcRenderer.invoke('restore-window'),
  setStartup: (enabled) => ipcRenderer.invoke('set-startup', enabled),
  getStartup: () => ipcRenderer.invoke('get-startup'),
  openExternal: (url) => ipcRenderer.send('open-external', url),
  checkUpdate: () => ipcRenderer.invoke('check-update'),
  updaterCheck: () => ipcRenderer.invoke('updater-check'),
  updaterDownload: () => ipcRenderer.invoke('updater-download'),
  updaterInstall: () => ipcRenderer.invoke('updater-install'),
  updaterStatus: () => ipcRenderer.invoke('updater-status'),
  onUpdaterEvent: (cb) => ipcRenderer.on('updater-event', (_e, payload) => cb(payload)),
  setOpacity: (v) => ipcRenderer.send('set-opacity', v),
  setCloseToTray: (enabled) => ipcRenderer.send('set-close-to-tray', enabled),
  handyEnter: (position) => ipcRenderer.invoke('handy-enter', position),
  handyExit: () => ipcRenderer.invoke('handy-exit'),
  handyExpand: (position, focus) => ipcRenderer.invoke('handy-expand', { position, focus }),
  handyCollapse: (position) => ipcRenderer.invoke('handy-collapse', position),
  handySetPosition: (position, open) => ipcRenderer.invoke('handy-set-position', { position, open }),
  setHandyShortcut: (accel) => ipcRenderer.invoke('set-handy-shortcut', accel),
  onToggleHandy: (cb) => ipcRenderer.on('toggle-handy', () => cb()),
  toggleMinimize: () => ipcRenderer.invoke('toggle-minimize'),
  toggleTray: () => ipcRenderer.invoke('toggle-tray'),
  pickImage: () => ipcRenderer.invoke('pick-image'),
  pickVideo: () => ipcRenderer.invoke('pick-video'),
  saveImage: (base64, ext) => ipcRenderer.invoke('save-image', base64, ext),
  saveMedia: (base64, ext) => ipcRenderer.invoke('save-media', base64, ext),
  // `ai` is { provider, model, apiKey, baseUrl, models } — see aiOpts() in the
  // renderer. `prompt` is only set for a custom AI action.
  improvePrompt: (text, ai) => ipcRenderer.invoke('improve-prompt', { text, ai }),
  aiTransform: (action, text, ai, prompt) => ipcRenderer.invoke('ai-transform', { action, text, ai, prompt }),
  chatMessage: (history, ai) => ipcRenderer.invoke('chat-message', { history, ai }),
  aiProviders: () => ipcRenderer.invoke('ai-providers'),
  // Asks the provider itself which models this key can use.
  aiListModels: (ai) => ipcRenderer.invoke('ai-list-models', { ai }),
  transcribeAudio: (base64, mimeType, opts) => ipcRenderer.invoke('transcribe-audio', base64, mimeType, opts),
  downloadImage: (filename) => ipcRenderer.invoke('download-image', filename),
  revealImage: (filename) => ipcRenderer.invoke('reveal-image', filename),
  copyImageToClipboard: (filename) => ipcRenderer.invoke('copy-image-clipboard', filename),
  pickFiles: () => ipcRenderer.invoke('pick-files'),
  saveFileAs: (storedName, name) => ipcRenderer.invoke('save-file-as', storedName, name),
  openFile: (storedName) => ipcRenderer.invoke('open-file', storedName),
  revealFile: (storedName) => ipcRenderer.invoke('reveal-file', storedName),
  deleteFile: (storedName) => ipcRenderer.invoke('delete-file', storedName),
  getStoragePath: () => ipcRenderer.invoke('get-storage-path'),
  pickStorageFolder: () => ipcRenderer.invoke('pick-storage-folder'),
  setStoragePath: (newBase) => ipcRenderer.invoke('set-storage-path', newBase),
  openStorageFolder: () => ipcRenderer.invoke('open-storage-folder'),
  exportData: () => ipcRenderer.invoke('export-data'),
  importData: () => ipcRenderer.invoke('import-data'),
  relaunchApp: () => ipcRenderer.send('relaunch-app'),
  exportNote: (name, content, ext) => ipcRenderer.invoke('export-note', name, content, ext),
  // { name, content, format, render? } — formats that carry the note's images
  exportNoteRich: (payload) => ipcRenderer.invoke('export-note-rich', payload),
  setQuickCapture: (enabled) => ipcRenderer.invoke('set-quick-capture', enabled),
  setQuickCaptureShortcut: (accel) => ipcRenderer.invoke('set-quick-capture-accel', accel),
  onQuickCapture: (cb) => ipcRenderer.on('quick-capture', () => cb()),
  qcSubmit: (payload) => ipcRenderer.send('qc-submit', payload),
  qcClose: () => ipcRenderer.send('qc-close'),
  onQcMessage: (cb) => ipcRenderer.on('qc-message', (_e, payload) => cb(payload)),
  notify: (payload) => ipcRenderer.invoke('notify', payload),
  stopFlash: () => ipcRenderer.send('stop-flash'),
  onNotificationClick: (cb) => ipcRenderer.on('notification-click', (_e, kind) => cb(kind))
});
