const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  loadNotes: () => ipcRenderer.invoke('load-notes'),
  saveNotes: (notes) => ipcRenderer.invoke('save-notes', notes),
  minimize: () => ipcRenderer.send('window-minimize'),
  close: () => ipcRenderer.send('window-close'),
  toggleAlwaysOnTop: () => ipcRenderer.invoke('toggle-always-on-top'),
  getAlwaysOnTop: () => ipcRenderer.invoke('get-always-on-top'),
  loadSettings: () => ipcRenderer.invoke('load-settings'),
  saveSettings: (settings) => ipcRenderer.invoke('save-settings', settings),
  setBgColor: (color) => ipcRenderer.send('set-bg-color', color),
  setStartup: (enabled) => ipcRenderer.invoke('set-startup', enabled),
  getStartup: () => ipcRenderer.invoke('get-startup'),
  openExternal: (url) => ipcRenderer.send('open-external', url),
  checkUpdate: () => ipcRenderer.invoke('check-update'),
  setOpacity: (v) => ipcRenderer.send('set-opacity', v),
  setCloseToTray: (enabled) => ipcRenderer.send('set-close-to-tray', enabled),
  pickImage: () => ipcRenderer.invoke('pick-image'),
  saveImage: (base64, ext) => ipcRenderer.invoke('save-image', base64, ext),
  downloadImage: (filename) => ipcRenderer.invoke('download-image', filename),
  revealImage: (filename) => ipcRenderer.invoke('reveal-image', filename),
  copyImageToClipboard: (filename) => ipcRenderer.invoke('copy-image-clipboard', filename),
  pickFiles: () => ipcRenderer.invoke('pick-files'),
  saveFileAs: (storedName, name) => ipcRenderer.invoke('save-file-as', storedName, name),
  openFile: (storedName) => ipcRenderer.invoke('open-file', storedName),
  revealFile: (storedName) => ipcRenderer.invoke('reveal-file', storedName),
  deleteFile: (storedName) => ipcRenderer.invoke('delete-file', storedName),
  getStoragePath: () => ipcRenderer.invoke('get-storage-path'),
  pickStorageFolder: () => ipcRenderer.invoke('pick-storage-folder'),
  setStoragePath: (newBase) => ipcRenderer.invoke('set-storage-path', newBase),
  openStorageFolder: () => ipcRenderer.invoke('open-storage-folder'),
  exportData: () => ipcRenderer.invoke('export-data'),
  importData: () => ipcRenderer.invoke('import-data'),
  relaunchApp: () => ipcRenderer.send('relaunch-app'),
  exportNote: (name, content, ext) => ipcRenderer.invoke('export-note', name, content, ext),
  setQuickCapture: (enabled) => ipcRenderer.invoke('set-quick-capture', enabled),
  onQuickCapture: (cb) => ipcRenderer.on('quick-capture', () => cb()),
  qcSubmit: (payload) => ipcRenderer.send('qc-submit', payload),
  qcClose: () => ipcRenderer.send('qc-close'),
  onQcMessage: (cb) => ipcRenderer.on('qc-message', (_e, payload) => cb(payload))
});
