// The in-app guide: what PromptPad can do, in English and Persian.
//
// Kept out of i18n.js on purpose. That file translates the *interface* — short
// strings, one per control, looked up by their English text. This is prose,
// paired with pictures, and it is read rather than clicked; mixing the two
// would make every UI translation lookup walk past a few thousand words of
// documentation.
//
// Each topic carries a screenshot from src/guide-images/, generated by
// tools/shoot-guide.js against the real app so the pictures cannot drift away
// from what the app actually looks like.
(function () {
  const TOPICS = [
    {
      id: 'basics',
      img: 'basics.png',
      title: { en: 'The workspace', fa: 'میز کار' },
      body: {
        en: [
          'Every prompt lives in its own tab down the left. Hit **new** to start one; the name comes from the first line, so you rarely have to type one.',
          '**Drag** tabs to reorder them, **right-click** for rename, duplicate, colour, export and more, and **Ctrl+click** to select several at once and act on all of them.',
          'Related tabs go in **groups** — drag one onto another, or pick a group from the right-click menu. Groups collapse, take a colour of their own, and can be exported whole.',
          'The rail itself folds away with **Ctrl+\\** when you want the page to yourself.'
        ],
        fa: [
          'هر پرامپت داخل تب خودش زندگی می‌کند، در ستون سمت چپ. برای شروع **new** را بزنید؛ نام تب از خط اول متن ساخته می‌شود، پس معمولاً لازم نیست چیزی تایپ کنید.',
          'تب‌ها را می‌شود **کشید** و جابه‌جا کرد، با **راست‌کلیک** تغییر نام داد، کپی کرد، رنگ داد یا خروجی گرفت، و با **Ctrl+کلیک** چندتا را با هم انتخاب کرد.',
          'تب‌های مرتبط را در **گروه** بگذارید — یکی را روی دیگری بکشید یا از منوی راست‌کلیک گروه را انتخاب کنید. گروه‌ها جمع می‌شوند، رنگ خودشان را دارند و یکجا خروجی گرفته می‌شوند.',
          'خود ستون تب‌ها با **Ctrl+\\** جمع می‌شود تا تمام پنجره برای نوشتن بماند.'
        ]
      }
    },
    {
      id: 'placeholders',
      img: 'placeholders.png',
      title: { en: 'Placeholders', fa: 'جای‌خالی‌ها' },
      body: {
        en: [
          'Write a blank as `[topic]` or `{name}` and PromptPad highlights it and offers a field to fill it in. Type a value and every copy of that blank in the note is filled at once.',
          'Give a blank a list and you get a dropdown instead of a text box: `[tone|formal, casual, funny]`.',
          '`[date]`, `[time]` and `[clipboard]` fill themselves in — the field opens with the value already in it, and you can still edit it.',
          'Fill several fields, then **Presets → Save typed values** to keep the whole set under a name. Next time, one click fills them all.'
        ],
        fa: [
          'جای خالی را به شکل `[موضوع]` یا `{نام}` بنویسید؛ پرامپت‌پد آن را هایلایت می‌کند و یک فیلد برای پر کردنش می‌دهد. مقدار را بنویسید و **همهٔ** تکرارهای آن در نوشته یکجا پر می‌شود.',
          'اگر به جای خالی یک لیست بدهید، به جای جعبهٔ متن یک منوی کشویی می‌گیرید: `[لحن|رسمی, خودمانی, طنز]`.',
          '`[date]` و `[time]` و `[clipboard]` خودشان پر می‌شوند — فیلد از همان اول مقدار را دارد و باز هم می‌توانید عوضش کنید.',
          'چند فیلد را پر کنید و بعد **Presets ← Save typed values** بزنید تا کل مجموعه زیر یک نام ذخیره شود. دفعهٔ بعد با یک کلیک همه‌شان پر می‌شوند.'
        ]
      }
    },
    {
      id: 'blocks',
      img: 'blocks.png',
      title: { en: 'Blocks and slash commands', fa: 'بلوک‌ها و دستورهای اسلش' },
      body: {
        en: [
          'A **block** is a reusable piece of a prompt — a persona, an output format, your standing rules. Type **@** in a note, pick one, and it drops in.',
          'Four are there to start with: `@persona`, `@json`, `@rules`, `@steps`. Add your own in Settings → Editor → Blocks, or select some text in a note and right-click → **Save as block**.',
          'A block can hold placeholders like any other text, and `$0` marks where the caret should land after it is inserted.',
          'Type **/** instead and you get commands: every AI action, a table, a code block, a heading, today\'s date. The text you typed to summon it is removed before the command runs.'
        ],
        fa: [
          '**بلوک** یک تکهٔ قابل استفادهٔ دوباره از پرامپت است — یک نقش، یک قالب خروجی، قانون‌های همیشگی خودتان. داخل نوشته **@** بزنید، یکی را انتخاب کنید، همان‌جا درج می‌شود.',
          'چهارتا از اول آماده‌اند: `@persona` و `@json` و `@rules` و `@steps`. مال خودتان را از Settings ← Editor ← Blocks اضافه کنید، یا متنی را در نوشته انتخاب کنید و راست‌کلیک ← **Save as block**.',
          'بلوک هم می‌تواند جای‌خالی داشته باشد، و `$0` مشخص می‌کند مکان‌نما بعد از درج کجا بایستد.',
          'به جایش **/** بزنید تا دستورها بیایند: همهٔ کارهای هوش مصنوعی، جدول، بلوک کد، تیتر، تاریخ امروز. متنی که برای صدا زدنش تایپ کرده‌اید قبل از اجرا پاک می‌شود.'
        ]
      }
    },
    {
      id: 'ai',
      img: 'ai.png',
      title: { en: 'AI, without an API key', fa: 'هوش مصنوعی، بدون کلید API' },
      body: {
        en: [
          '**Improve Prompt** rewrites your draft into something clearer and more effective — the whole note, a line you selected, or a single code block in the markdown preview.',
          'Right-click the Improve button (or use the **AI actions** menu) for more: translate between Persian and English, summarise, fix grammar, or change the tone. You can save your own instructions as one-click actions.',
          '**AI Chat** sits in the rail for quick questions without leaving the app — one continuous conversation, cleared whenever you like.',
          'The **mic** turns speech into text at the caret, in Persian or English, detected automatically.'
        ],
        fa: [
          '**Improve Prompt** پیش‌نویس شما را به یک پرامپت واضح‌تر و مؤثرتر بازنویسی می‌کند — کل نوشته، یا فقط خطی که انتخاب کرده‌اید، یا حتی یک بلوک کد در پیش‌نمایش مارک‌داون.',
          'روی دکمهٔ Improve راست‌کلیک کنید (یا از منوی **AI actions**) تا بقیه بیایند: ترجمهٔ فارسی ↔ انگلیسی، خلاصه‌سازی، اصلاح گرامر، یا تغییر لحن. دستور دلخواه خودتان را هم می‌شود به‌عنوان یک اکشن ذخیره کرد.',
          '**AI Chat** در ستون کناری است برای سؤال‌های سریع بدون خارج شدن از برنامه — یک گفتگوی پیوسته که هر وقت خواستید پاکش می‌کنید.',
          'دکمهٔ **میکروفن** گفتار را همان‌جا که مکان‌نما هست به متن تبدیل می‌کند، فارسی یا انگلیسی، با تشخیص خودکار.'
        ]
      }
    },
    {
      id: 'fastsave',
      img: 'fastsave.png',
      title: { en: 'Fast Save and quick capture', fa: 'ذخیرهٔ سریع' },
      body: {
        en: [
          '**Fast Save** is a chat with yourself, pinned above your tabs. Type, press Enter, and it is kept with a timestamp — copy, edit or delete any message later.',
          'Paste or attach **images and files** with a caption, search everything you have saved, and browse the pictures in a media gallery.',
          'Press **Ctrl+Shift+Space** anywhere — even with PromptPad hidden — and a small box appears. Type or paste, hit Enter, and it lands in Fast Save without you ever switching windows.'
        ],
        fa: [
          '**Fast Save** یک گفتگو با خودتان است که بالای تب‌ها سنجاق شده. بنویسید، Enter بزنید، با زمانش ذخیره می‌شود — بعداً می‌توانید هر پیام را کپی، ویرایش یا حذف کنید.',
          '**عکس و فایل** را با توضیح بچسبانید یا پیوست کنید، در هر چه ذخیره کرده‌اید جستجو کنید، و عکس‌ها را در گالری مرور کنید.',
          'هر جا که باشید **Ctrl+Shift+Space** را بزنید — حتی وقتی پرامپت‌پد پنهان است — یک جعبهٔ کوچک باز می‌شود. بنویسید یا بچسبانید و Enter؛ مستقیم می‌رود داخل Fast Save بدون اینکه پنجره عوض کنید.'
        ]
      }
    },
    {
      id: 'themes',
      img: 'themes.png',
      title: { en: 'Themes', fa: 'پوسته‌ها' },
      body: {
        en: [
          'Settings → **Theme** is a board of every theme, each card a miniature of the app in that theme. **Hover** one and the real window takes it on; stay on it a moment longer and its effect starts running too. Click to keep it.',
          '**Dark** and **Light** are plain palettes. The rest do something:',
          '**Reactive** answers your keyboard — ink soaks under the words, a cut opens where you type, deleted text lingers. **Nature** runs on its own: storms, aurora, embers, koi. **Machines** are screens and instruments — an old CRT, glyph rain, a blueprint, a 32-bit snow level.',
          '**Live** reads the real world: the time of day, the calendar, the phase of tonight\'s moon, the music coming out of your speakers. **Sound** you hear. **Playable** you can put your hand into. **Luxury** is the app rendered in a material.',
          'Star the ones you keep coming back to and they sort to the front.'
        ],
        fa: [
          'Settings ← **Theme** یک تختهٔ کامل از همهٔ پوسته‌هاست و هر کارت، تصویر کوچک خود برنامه با آن پوسته است. روی یکی **هاور** کنید تا پنجرهٔ واقعی همان شکل شود؛ کمی بیشتر بمانید تا افکتش هم اجرا شود. کلیک کنید تا بماند.',
          '**Dark** و **Light** فقط پالت رنگ‌اند. بقیه کاری می‌کنند:',
          '**Reactive** به تایپ شما جواب می‌دهد — جوهر زیر کلمه‌ها پخش می‌شود، جای تایپ زخم باز می‌شود، متن پاک‌شده چند لحظه می‌ماند. **Nature** خودش کار می‌کند: طوفان، شفق، اخگر، ماهی کوی. **Machines** صفحه‌ها و ابزارهای دقیق‌اند — تلویزیون قدیمی، باران حروف، نقشهٔ فنی، یک مرحلهٔ برفی ۳۲ بیتی.',
          '**Live** دنیای واقعی را می‌خواند: ساعت، تقویم، فاز واقعی ماه امشب، و صدایی که از بلندگو پخش می‌شود. **Sound** را می‌شنوید. **Playable** را با موس دست می‌زنید. **Luxury** یعنی برنامه از جنس یک ماده.',
          'هر کدام را که مدام برمی‌گردید سراغش ستاره بزنید تا اول لیست بیاید.'
        ]
      }
    },
    {
      id: 'lock',
      img: 'lock.png',
      title: { en: 'Locking a note', fa: 'قفل کردن نوشته' },
      body: {
        en: [
          'Right-click a tab → **Lock note**. Its text is encrypted on disk with a key derived from a PIN you choose. PromptPad never stores the PIN, so nobody — including a reinstall — can reset it.',
          'That is why you get a **recovery code** when you set the lock up. It is the only other way in. Write it down.',
          'Unlocking opens every locked note for the session; **Lock now** in Settings → Data shuts them again, and so does quitting. A locked note\'s history is encrypted along with its text, and its name in the rail never shows the first line.'
        ],
        fa: [
          'روی تب راست‌کلیک کنید ← **Lock note**. متن آن روی دیسک رمزنگاری می‌شود، با کلیدی که از پینِ انتخابی شما ساخته شده. پرامپت‌پد پین را هیچ‌جا ذخیره نمی‌کند، پس هیچ‌کس — حتی نصب دوباره — نمی‌تواند بازنشانی‌اش کند.',
          'به همین دلیل موقع ساختن قفل یک **کد بازیابی** می‌گیرید. تنها راه دیگر ورود همان است. یادداشتش کنید.',
          'باز کردن قفل، همهٔ نوشته‌های قفل‌شده را برای همان نشست باز می‌کند؛ **Lock now** در Settings ← Data دوباره می‌بنددشان، بستن برنامه هم همین‌طور. تاریخچهٔ نوشتهٔ قفل‌شده هم همراه متنش رمز می‌شود، و نامش در ستون تب‌ها هرگز خط اول را نشان نمی‌دهد.'
        ]
      }
    },
    {
      id: 'handy',
      img: 'handy.png',
      title: { en: 'Out of the way', fa: 'از سر راه' },
      body: {
        en: [
          '**Handy dock** collapses the whole window to a thin line at the edge of the screen. Hover it and the notepad slides open; move away and it tucks back. Toggle it with **Ctrl+Shift+D**.',
          '**Focus mode** (**Ctrl+Shift+F**) hides every bit of chrome and leaves the text. **Esc** brings it back.',
          '**Ctrl+P** opens the command palette: jump to any tab, or run a command, without reaching for the mouse.',
          'The window floats above your other apps by default — the pin in the title bar turns that off.'
        ],
        fa: [
          '**Handy dock** کل پنجره را به یک نوار باریک در لبهٔ صفحه جمع می‌کند. رویش هاور کنید تا باز شود؛ کنار بروید تا دوباره جمع شود. با **Ctrl+Shift+D** روشن و خاموش می‌شود.',
          '**Focus mode** (**Ctrl+Shift+F**) همهٔ حاشیه‌ها را پنهان می‌کند و فقط متن می‌ماند. با **Esc** برمی‌گردد.',
          '**Ctrl+P** پالت دستورها را باز می‌کند: بدون دست بردن به موس به هر تبی بپرید یا هر دستوری را اجرا کنید.',
          'پنجره به‌طور پیش‌فرض روی بقیهٔ برنامه‌ها می‌ماند — سنجاق نوار عنوان این را خاموش می‌کند.'
        ]
      }
    },
    {
      id: 'share',
      img: 'share.png',
      title: { en: 'Discover and shared notes', fa: 'دیسکاور و نوشتهٔ مشترک' },
      body: {
        en: [
          '**Discover** is a shared prompt gallery. Browse by category, search, like the good ones, and hit **Use** to drop any prompt into a new tab. Publish your own with a title, a category and a picture.',
          'Right-click a tab → **Share & invite** and someone else can join the note. You both edit the same text live, with a bar above the editor showing who is in it and who is typing. Invite people as an editor or a read-only viewer.',
          'Both need a free Discover account, and both can be turned off in Settings → Tabs if you would rather PromptPad stayed offline.'
        ],
        fa: [
          '**Discover** یک گالری مشترک از پرامپت‌هاست. بر اساس دسته‌بندی مرور کنید، جستجو کنید، خوب‌ها را لایک کنید، و با **Use** هر پرامپتی را داخل یک تب تازه بیندازید. مال خودتان را هم با عنوان و دسته و عکس منتشر کنید.',
          'روی تب راست‌کلیک کنید ← **Share & invite** تا کس دیگری وارد نوشته شود. هر دو زنده روی یک متن می‌نویسید و نواری بالای ویرایشگر نشان می‌دهد چه کسی داخل است و چه کسی دارد تایپ می‌کند. می‌توانید کسی را ویرایشگر یا فقط بیننده دعوت کنید.',
          'هر دو به یک حساب رایگان Discover نیاز دارند، و هر دو را می‌شود از Settings ← Tabs خاموش کرد اگر ترجیح می‌دهید پرامپت‌پد آفلاین بماند.'
        ]
      }
    }
  ];

  window.PP_GUIDE = TOPICS;
})();
